steps:
  # Étape 0 : Copier la clé JSON depuis le Secret Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Fetching the service account key from Secret Manager..."
        gcloud secrets versions access latest --secret=my-service-account-key > /workspace/service-account-key.json
        cat /workspace/service-account-key.json # Ajoutez cette ligne pour vérifier le contenu

  # Étape 1 : Construire l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/helpdesk-app', '.']

  # Étape 2 : Pousser l'image Docker vers Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/helpdesk-app']

  # Étape 3 : Déployer le job Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud beta run jobs update helpdesk-job --image gcr.io/$PROJECT_ID/helpdesk-app --region europe-west1 || \
        gcloud beta run jobs create helpdesk-job --image gcr.io/$PROJECT_ID/helpdesk-app --region europe-west1

timeout: "1200s"  # Exemple de timeout, ajustez selon vos besoins

options:
  defaultLogsBucketBehavior: "REGIONAL_USER_OWNED_BUCKET"

images:
  - 'gcr.io/$PROJECT_ID/helpdesk-app'

