steps:
  # Étape 0 : Copier la clé JSON depuis le Secret Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Fetching the service account key from Secret Manager..."
        gcloud secrets versions access latest --secret=my-service-account-key > /workspace/service-account-key.json
        export SERVICE_ACCOUNT_KEY_JSON=$(cat /workspace/service-account-key.json | base64)

  # Étape 1 : Construire l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/helpdesk-app', '.']
    env:
      - 'SERVICE_ACCOUNT_KEY_JSON=$(cat /workspace/service-account-key.json)'

  # Étape 2 : Pousser l'image Docker vers Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/helpdesk-app']

  # Étape 3 : Déployer le service Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy help-desk-service --image gcr.io/$PROJECT_ID/helpdesk-app --region europe-west9 --platform managed --allow-unauthenticated

timeout: "1200s"  # Exemple de timeout, ajustez selon vos besoins

options:
  defaultLogsBucketBehavior: "REGIONAL_USER_OWNED_BUCKET"

substitutions:
  _GCP_PROJECT: $PROJECT_ID

images:
  - 'gcr.io/$PROJECT_ID/helpdesk-app'

